Sprint1/step2
Aleksandr-Abramov/react-burger pull request #2
Opened 2023-02-17 13:14 UTC by Aleksandr-Abramov

Здравствуйте, надеюсь критических замечаний не будет.

2023-02-17 17:34 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа! Вы хорошо разобрались с useEffect и PropTypes.

Что понравилось:
- Есть скролл по категориям
- Хорошая типизация пропсов
- Используется `useMemo`
- Есть отписка от слушателя событий

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Вынести модалки и управление ими из компонента `App` - более подробно описание проблемы смотрите комментарии в pull request.
- При попытке закрыть модалку по ESC появляется ошибка в консоли.
<img width="1439" alt="Снимок экрана 2023-02-17 в 20 28 55" src="https://user-images.githubusercontent.com/60173362/219723999-ada9f248-7e3f-4a0b-8d36-625b649220a3.png">

- у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

Удачных правок!

2023-02-17 17:34 UTC, andryxxa93 commented on src/App.tsx
> +        console.log(`во время получения ингридиентов произошла ошибка ${err}`)
**Можно улучшить**
Console.log нужен только для процесса разработки, перед сдачей проекта его нужно удалять, иначе она будет загружать консоль ненужной, а возможно и приватной информацией. А ошибку лучше записывать в state и показывать пользователю, чтобы он понимал, что происходит.

2023-02-17 17:34 UTC, andryxxa93 commented on src/App.tsx
> +        </ModalOverlay>
**Необходимо исправить**
Компонент `App` это композиционный компонент, в котором должно быть по-минимуму логики. Компоненту не стоит знать как управляются модалки - их и логику управления стоит вынести в компоненты, к которым они относятся - `BurgerIngredients ` и `BurgerConstructor `

2023-02-17 17:34 UTC, andryxxa93 commented on src/components/modal-overlay/ModalOverlay.jsx
> +const ModalOverlay = ({ children, handlerModelClose }) => {
**Надо исправить**

у ModalOverlay не должно быть children, это просто компонент подложки а не контейнер`

2023-02-17 17:34 UTC, andryxxa93 commented on src/components/modal/Modal.jsx
> +      document.removeEventListener("keydown", closePopup);
**Отлично!**
Вы сделали отписку от слушателя, это позволит избежать утечек памяти.

2023-02-17 17:34 UTC, andryxxa93 commented on src/utils/data.js
> +export let data = [
**Можно лучше**
Эти данные больше не потребуются их можно удалить

2023-02-17 17:34 UTC, andryxxa93 commented on tsconfig.json
> +    "jsx": "react-jsx",
**Можно лучше**
Этот файл сейчас не нужен его можно удалить, так как `typescript` будет только в будущих спринтах.

2023-02-20 12:03 UTC, Aleksandr-Abramov commented on src/App.tsx
> +        console.log(`во время получения ингридиентов произошла ошибка ${err}`)
Подумал, что на данном этапе. Будет уместно, сделать сделать popup для ошибок. Вместо console.log.

2023-02-20 12:07 UTC, Aleksandr-Abramov commented on src/App.tsx
> +        </ModalOverlay>
Убрал все компоненты, в соответствующие места. На прошлом году обучения. В теории предлагали, держать все попапы в компоненте App. Почему сейчас по другому? И, где принято держать попапы?

2023-02-20 12:25 UTC, Aleksandr-Abramov commented on src/components/modal-overlay/ModalOverlay.jsx
> +const ModalOverlay = ({ children, handlerModelClose }) => {
Не совсем понял, почему у ModalOverlay не должно быть children. У меня получилась такая структура(ModalOverlay > Modal > наполнение(children)). В теории, есть несколько пунктов на этот счет:"Modal — компонент самого модального окна: шапка с заголовком и иконка закрытия. ModalOverlay — фоновая подложка под модальным окном." Если, я правильно понял автора. Он хочет, сделать изолированную подложку ModalOverlay и Model. Подложка нужна для портала. Остальные компоненты вложенные в нее, автоматически попадают в портал. Model как обертка с кнопкой закрытия. Куда можно складывать любой контент. Если изменить структуру," <Modal> {children} <ModalOverlay /> </Modal> " поедет вся верстка. Предлагаю, оставить верстку как есть. Перенес компонент ModalOverlay в Modal

2023-02-20 20:35 UTC, andryxxa93 commented on src/App.tsx
> +        </ModalOverlay>
Там можно их держать, но сам компонент App от этого становится больше, хотя его функция это просто сбор всех основных блоков воедино + немного изначальной логики. Ему совершенно нет необходимости что-то знать про управление модальными окнами.

2023-02-20 20:42 UTC, andryxxa93 requested changes
- При запуске проекта возникает ошибка. Чтобы её убрать рекомендую поменять расширение у `App` c `tsx` на `jsx`.
<img width="920" alt="Снимок экрана 2023-02-20 в 23 39 42" src="https://user-images.githubusercontent.com/60173362/220195324-2b6d6106-05c1-4fa2-838a-8740a3ccd375.png">

- При запуске возникает такое диалоговое окно. Хотя никаких ошибок в запросе не было.
<img width="1440" alt="Снимок экрана 2023-02-20 в 23 38 55" src="https://user-images.githubusercontent.com/60173362/220195600-8651f248-04bd-498d-b917-69b374961f44.png">

2023-02-21 12:31 UTC, andryxxa93 approved these changes
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-03-14 14:32 UTC, merged