features: добавил типизацию typeScript
Aleksandr-Abramov/react-burger pull request #5
Opened 2023-06-15 09:53 UTC by Aleksandr-Abramov

2023-06-21 13:14 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Проект теперь типизирован;

### **Но есть несколько замечаний, которые нужно исправить:**

- index.js (в src) тоже нужно перевести на ts.
- Оставил замечания в коде;

### **Сделает код лучше:**

- Используйте типизированные useSelector и useDispatch, тогда вам не нужно будет писать везде any. <https://redux.js.org/usage/usage-with-typescript#define-root-state-and-dispatch-types>;

### **После исправления всех замечаний, работа будет принята)**

2023-06-21 13:14 UTC, ArslanMustafin commented on src/components/app/App.tsx
> +  const handlerModelClose = (e: React.BaseSyntheticEvent<HTMLElement> | React.MouseEvent<HTMLButtonElement>) => {
**Можно лучше:**

Длинные типы лучше вынести в отдельный тип.
А у вас вроде бы этот тип повторяется)) поэтому лучше будет вынести и переиспользовать

2023-06-21 13:14 UTC, ArslanMustafin commented on src/components/burger-constructor/drag-card/DragCard.tsx
> +      const clientOffset: any = monitor.getClientOffset();
**Надо исправить:**

не совсем понял зачем тут any?)
метод типизирован, и он возвращает `XYCoord | null`.  вам нужно просто сказать ts  что null там быть не может)

https://disk.yandex.com/i/XEk0bA52vupaVQ

2023-06-21 13:14 UTC, ArslanMustafin commented on src/components/burger-ingredients/BurgerIngredients.tsx
>    });
**Надо исправить:**

здесь не должно быть типа any) вам просто нужно показать тайпскрипту что там не будет undefined значения. Для этого просто используйте опциональную цепочку:

```js
bunElement?.target.scrollIntoView({...});
```

тоже самое и с другими)

2023-06-21 13:14 UTC, ArslanMustafin commented on src/components/modal/Modal.tsx
> +  handlerModelClose: (e: any) => void;
**Надо исправить:**

здесь не должно быть типа any)

2023-06-21 13:14 UTC, ArslanMustafin commented on src/components/modal-overlay/ModalOverlay.tsx
> +  handlerModelClose: (e: any) => void;
**Надо исправить:**

здесь не должно быть типа any)

2023-06-22 19:09 UTC, Aleksandr-Abramov commented
Arslan Mustafin, здравствуйте. Внес необходимые изменения. Предлагаю, оставить типизацию useSelector и useDispatch, до следующего спринта. Там, как раз рассматривается типизация redux. Я, совсем не знаю английского. По этому, хочу дождаться материала на русском.

2023-06-23 07:22 UTC, ArslanMustafin commented
> Arslan Mustafin, здравствуйте. Внес необходимые изменения. Предлагаю, оставить типизацию useSelector и useDispatch, до следующего спринта. Там, как раз рассматривается типизация redux. Я, совсем не знаю английского. По этому, хочу дождаться материала на русском.

Добрый день)) да поэтому я и поставил этот пункт в можно лучше (он необязателен к исполнению)

2023-06-23 07:43 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть 1 замечание, которое нужно исправить:**

- у вас возникает вот такая ошибка: <https://disk.yandex.com/i/NjD-nPmNrqr8gw>. Вы забыли тут тип поменять на `handlerModelClose`.

  А также:

1.   Тут вам не нужно закрывать модальное окно ингредиентов и очищать их.
2.   Проверку на то, что была нажата клавиша `Esc` делать не нужно. Вы это делаете в компоненте `modal`.
3.  Лучше вообще не передавать Event, просто сделать вот так (это не обязательно, но если можете, то исправьте):


  ```js
  // Аналогично и с другими handlerModelClose
  function handlerModelClose() {
    dispatch(closeOrderPopup());
  }

  // и вот такую структуру модального окна

  <>
    <ModalOverlay onClose={handleModalClose} />
    <div className={styles.modal}>...</div>
  <>
  ```

2023-06-23 07:43 UTC, ArslanMustafin commented on src/components/burger-constructor/BurgerConstructor.tsx
> +  function handlerModelClose(e: React.BaseSyntheticEvent<HTMLElement> | React.MouseEvent<HTMLButtonElement> ) {
**Надо исправить:**

у вас возникает вот такая ошибка: https://disk.yandex.com/i/NjD-nPmNrqr8gw. Вы забыли тут тип поменять на `handlerModelClose`.

А также: 

1. Тут вам не нужно закрывать модальное окно ингредиентов и очищать их.
2. Проверку на то, что была нажата клавиша `Esc` делать не нужно. Вы это делаете в компоненте `modal`.
3. Лучше вообще не передавать Event, просто сделать вот так (это не обязательно, но если можете, то исправьте):

```js
// Аналогично и с другими handlerModelClose
function handlerModelClose() {
  dispatch(closeOrderPopup());
}

// и вот такую структуру модального окна
<>
  <ModalOverlay onClose={handleModalClose} />
  <div className={styles.modal}>...</div>
<>
```

2023-06-23 09:38 UTC, Aleksandr-Abramov commented
Arslan, здравствуйте. В целом все поправил. Третий пункт, думаю оставить как есть. Иначе, придется в нескольких компонентах HTML править. Спасибо за советы, комментарии. :+1:

2023-06-23 16:18 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-07-09 11:38 UTC, merged